### ISSUE TITLE
Installation on macOS Big Sur fails

### ISSUE THREAD

**Issue by khider** [jakobrunge/tigramite#159]
Tried it 2 ways:
1. pip install trigamite: 

```
 ERROR: Command errored out with exit status 1:
   command: /Users/deborahkhider/opt/anaconda3/envs/causality/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-install-i6ehv5i6/tigramite_2686b69ec0604d8b8ee421651fd7b40f/setup.py'"'"'; __file__='"'"'/private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-install-i6ehv5i6/tigramite_2686b69ec0604d8b8ee421651fd7b40f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-wheel-l228w08p
       cwd: /private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-install-i6ehv5i6/tigramite_2686b69ec0604d8b8ee421651fd7b40f/
  Complete output (39 lines):
  Cython cannot be found. Skipping generation of C code from cython and using pre-compiled C code instead
  /Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    warnings.warn(
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.9
  creating build/lib.macosx-10.9-x86_64-3.9/tigramite
  copying tigramite/models.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite
  copying tigramite/pcmci.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite
  copying tigramite/plotting.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite
  copying tigramite/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite
  copying tigramite/data_processing.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite
  creating build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
  copying tigramite/independence_tests/independence_tests_base.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
  copying tigramite/independence_tests/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
  copying tigramite/independence_tests/parcorr.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
  copying tigramite/independence_tests/LBFGS.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
  copying tigramite/independence_tests/gpdc_torch.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
  copying tigramite/independence_tests/cmisymb.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
  copying tigramite/independence_tests/oracle_conditional_independence.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
  copying tigramite/independence_tests/cmiknn.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
  copying tigramite/independence_tests/gpdc.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
  running build_ext
  building 'tigramite.tigramite_cython_code' extension
  creating build/temp.macosx-10.9-x86_64-3.9
  creating build/temp.macosx-10.9-x86_64-3.9/private
  creating build/temp.macosx-10.9-x86_64-3.9/private/var
  creating build/temp.macosx-10.9-x86_64-3.9/private/var/folders
  creating build/temp.macosx-10.9-x86_64-3.9/private/var/folders/xj
  creating build/temp.macosx-10.9-x86_64-3.9/private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn
  creating build/temp.macosx-10.9-x86_64-3.9/private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T
  creating build/temp.macosx-10.9-x86_64-3.9/private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-install-i6ehv5i6
  creating build/temp.macosx-10.9-x86_64-3.9/private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-install-i6ehv5i6/tigramite_2686b69ec0604d8b8ee421651fd7b40f
  creating build/temp.macosx-10.9-x86_64-3.9/private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-install-i6ehv5i6/tigramite_2686b69ec0604d8b8ee421651fd7b40f/tigramite
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/deborahkhider/opt/anaconda3/envs/causality/include -fPIC -O2 -isystem /Users/deborahkhider/opt/anaconda3/envs/causality/include -I/Users/deborahkhider/opt/anaconda3/envs/causality/include/python3.9 -I/Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/site-packages/numpy/core/include -c /private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-install-i6ehv5i6/tigramite_2686b69ec0604d8b8ee421651fd7b40f/tigramite/tigramite_cython_code.c -o build/temp.macosx-10.9-x86_64-3.9/private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-install-i6ehv5i6/tigramite_2686b69ec0604d8b8ee421651fd7b40f/tigramite/tigramite_cython_code.o -fopenmp
  clang: error: unsupported option '-fopenmp'
  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for tigramite
  Running setup.py clean for tigramite
Failed to build tigramite
Installing collected packages: scipy, tigramite
    Running setup.py install for tigramite ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/deborahkhider/opt/anaconda3/envs/causality/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-install-i6ehv5i6/tigramite_2686b69ec0604d8b8ee421651fd7b40f/setup.py'"'"'; __file__='"'"'/private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-install-i6ehv5i6/tigramite_2686b69ec0604d8b8ee421651fd7b40f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-record-s0k4ps94/install-record.txt --single-version-externally-managed --compile --install-headers /Users/deborahkhider/opt/anaconda3/envs/causality/include/python3.9/tigramite
         cwd: /private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-install-i6ehv5i6/tigramite_2686b69ec0604d8b8ee421651fd7b40f/
    Complete output (41 lines):
    Cython cannot be found. Skipping generation of C code from cython and using pre-compiled C code instead
    /Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
      warnings.warn(
    running install
    /Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.9
    creating build/lib.macosx-10.9-x86_64-3.9/tigramite
    copying tigramite/models.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite
    copying tigramite/pcmci.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite
    copying tigramite/plotting.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite
    copying tigramite/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite
    copying tigramite/data_processing.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite
    creating build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
    copying tigramite/independence_tests/independence_tests_base.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
    copying tigramite/independence_tests/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
    copying tigramite/independence_tests/parcorr.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
    copying tigramite/independence_tests/LBFGS.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
    copying tigramite/independence_tests/gpdc_torch.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
    copying tigramite/independence_tests/cmisymb.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
    copying tigramite/independence_tests/oracle_conditional_independence.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
    copying tigramite/independence_tests/cmiknn.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
    copying tigramite/independence_tests/gpdc.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
    running build_ext
    building 'tigramite.tigramite_cython_code' extension
    creating build/temp.macosx-10.9-x86_64-3.9
    creating build/temp.macosx-10.9-x86_64-3.9/private
    creating build/temp.macosx-10.9-x86_64-3.9/private/var
    creating build/temp.macosx-10.9-x86_64-3.9/private/var/folders
    creating build/temp.macosx-10.9-x86_64-3.9/private/var/folders/xj
    creating build/temp.macosx-10.9-x86_64-3.9/private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn
    creating build/temp.macosx-10.9-x86_64-3.9/private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T
    creating build/temp.macosx-10.9-x86_64-3.9/private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-install-i6ehv5i6
    creating build/temp.macosx-10.9-x86_64-3.9/private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-install-i6ehv5i6/tigramite_2686b69ec0604d8b8ee421651fd7b40f
    creating build/temp.macosx-10.9-x86_64-3.9/private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-install-i6ehv5i6/tigramite_2686b69ec0604d8b8ee421651fd7b40f/tigramite
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/deborahkhider/opt/anaconda3/envs/causality/include -fPIC -O2 -isystem /Users/deborahkhider/opt/anaconda3/envs/causality/include -I/Users/deborahkhider/opt/anaconda3/envs/causality/include/python3.9 -I/Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/site-packages/numpy/core/include -c /private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-install-i6ehv5i6/tigramite_2686b69ec0604d8b8ee421651fd7b40f/tigramite/tigramite_cython_code.c -o build/temp.macosx-10.9-x86_64-3.9/private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-install-i6ehv5i6/tigramite_2686b69ec0604d8b8ee421651fd7b40f/tigramite/tigramite_cython_code.o -fopenmp
    clang: error: unsupported option '-fopenmp'
    error: command '/usr/bin/clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/deborahkhider/opt/anaconda3/envs/causality/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-install-i6ehv5i6/tigramite_2686b69ec0604d8b8ee421651fd7b40f/setup.py'"'"'; __file__='"'"'/private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-install-i6ehv5i6/tigramite_2686b69ec0604d8b8ee421651fd7b40f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/pip-record-s0k4ps94/install-record.txt --single-version-externally-managed --compile --install-headers /Users/deborahkhider/opt/anaconda3/envs/causality/include/python3.9/tigramite Check the logs for full command output.
```

When going through python3 setup.py install

```
tuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  warnings.warn(
running install
/Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating tigramite.egg-info
writing tigramite.egg-info/PKG-INFO
writing dependency_links to tigramite.egg-info/dependency_links.txt
writing requirements to tigramite.egg-info/requires.txt
writing top-level names to tigramite.egg-info/top_level.txt
writing manifest file 'tigramite.egg-info/SOURCES.txt'
reading manifest file 'tigramite.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.pxd' anywhere in distribution
writing manifest file 'tigramite.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.macosx-10.9-x86_64-3.9
creating build/lib.macosx-10.9-x86_64-3.9/tigramite
copying tigramite/models.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite
copying tigramite/pcmci.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite
copying tigramite/plotting.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite
copying tigramite/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite
copying tigramite/data_processing.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite
creating build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
copying tigramite/independence_tests/independence_tests_base.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
copying tigramite/independence_tests/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
copying tigramite/independence_tests/parcorr.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
copying tigramite/independence_tests/LBFGS.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
copying tigramite/independence_tests/gpdc_torch.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
copying tigramite/independence_tests/cmisymb.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
copying tigramite/independence_tests/oracle_conditional_independence.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
copying tigramite/independence_tests/cmiknn.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
copying tigramite/independence_tests/gpdc.py -> build/lib.macosx-10.9-x86_64-3.9/tigramite/independence_tests
running build_ext
building 'tigramite.tigramite_cython_code' extension
creating build/temp.macosx-10.9-x86_64-3.9
creating build/temp.macosx-10.9-x86_64-3.9/Users
creating build/temp.macosx-10.9-x86_64-3.9/Users/deborahkhider
creating build/temp.macosx-10.9-x86_64-3.9/Users/deborahkhider/Documents
creating build/temp.macosx-10.9-x86_64-3.9/Users/deborahkhider/Documents/GitHub
creating build/temp.macosx-10.9-x86_64-3.9/Users/deborahkhider/Documents/GitHub/tigramite
creating build/temp.macosx-10.9-x86_64-3.9/Users/deborahkhider/Documents/GitHub/tigramite/tigramite
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/deborahkhider/opt/anaconda3/envs/causality/include -fPIC -O2 -isystem /Users/deborahkhider/opt/anaconda3/envs/causality/include -I/Users/deborahkhider/opt/anaconda3/envs/causality/include/python3.9 -I/Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/site-packages/numpy/core/include -c /Users/deborahkhider/Documents/GitHub/tigramite/tigramite/tigramite_cython_code.c -o build/temp.macosx-10.9-x86_64-3.9/Users/deborahkhider/Documents/GitHub/tigramite/tigramite/tigramite_cython_code.o -fopenmp
clang: error: unsupported option '-fopenmp'
error: command '/usr/bin/clang' failed with exit code 1
(causality) 169-231-146-156:tigramite deborahkhider$ checkout developer
-bash: checkout: command not found
(causality) 169-231-146-156:tigramite deborahkhider$ git checkout developer
Branch 'developer' set up to track remote branch 'developer' from 'origin'.
Switched to a new branch 'developer'
(causality) 169-231-146-156:tigramite deborahkhider$ python3 setup.py install
/Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  warnings.warn(
running install
/Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing tigramite.egg-info/PKG-INFO
writing dependency_links to tigramite.egg-info/dependency_links.txt
writing requirements to tigramite.egg-info/requires.txt
writing top-level names to tigramite.egg-info/top_level.txt
reading manifest file 'tigramite.egg-info/SOURCES.txt'
writing manifest file 'tigramite.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_py
creating build/lib
creating build/lib/tigramite
copying tigramite/lpcmci.py -> build/lib/tigramite
copying tigramite/models.py -> build/lib/tigramite
copying tigramite/pcmci.py -> build/lib/tigramite
copying tigramite/plotting.py -> build/lib/tigramite
copying tigramite/__init__.py -> build/lib/tigramite
copying tigramite/causal_effects.py -> build/lib/tigramite
copying tigramite/data_processing.py -> build/lib/tigramite
creating build/lib/tigramite/independence_tests
copying tigramite/independence_tests/independence_tests_base.py -> build/lib/tigramite/independence_tests
copying tigramite/independence_tests/__init__.py -> build/lib/tigramite/independence_tests
copying tigramite/independence_tests/parcorr.py -> build/lib/tigramite/independence_tests
copying tigramite/independence_tests/LBFGS.py -> build/lib/tigramite/independence_tests
copying tigramite/independence_tests/gpdc_torch.py -> build/lib/tigramite/independence_tests
copying tigramite/independence_tests/cmisymb.py -> build/lib/tigramite/independence_tests
copying tigramite/independence_tests/oracle_conditional_independence.py -> build/lib/tigramite/independence_tests
copying tigramite/independence_tests/cmiknn.py -> build/lib/tigramite/independence_tests
copying tigramite/independence_tests/gpdc.py -> build/lib/tigramite/independence_tests
creating build/bdist.macosx-10.9-x86_64
creating build/bdist.macosx-10.9-x86_64/egg
creating build/bdist.macosx-10.9-x86_64/egg/tigramite
copying build/lib/tigramite/lpcmci.py -> build/bdist.macosx-10.9-x86_64/egg/tigramite
copying build/lib/tigramite/models.py -> build/bdist.macosx-10.9-x86_64/egg/tigramite
copying build/lib/tigramite/pcmci.py -> build/bdist.macosx-10.9-x86_64/egg/tigramite
copying build/lib/tigramite/plotting.py -> build/bdist.macosx-10.9-x86_64/egg/tigramite
copying build/lib/tigramite/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/tigramite
copying build/lib/tigramite/causal_effects.py -> build/bdist.macosx-10.9-x86_64/egg/tigramite
copying build/lib/tigramite/data_processing.py -> build/bdist.macosx-10.9-x86_64/egg/tigramite
creating build/bdist.macosx-10.9-x86_64/egg/tigramite/independence_tests
copying build/lib/tigramite/independence_tests/independence_tests_base.py -> build/bdist.macosx-10.9-x86_64/egg/tigramite/independence_tests
copying build/lib/tigramite/independence_tests/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/tigramite/independence_tests
copying build/lib/tigramite/independence_tests/parcorr.py -> build/bdist.macosx-10.9-x86_64/egg/tigramite/independence_tests
copying build/lib/tigramite/independence_tests/LBFGS.py -> build/bdist.macosx-10.9-x86_64/egg/tigramite/independence_tests
copying build/lib/tigramite/independence_tests/gpdc_torch.py -> build/bdist.macosx-10.9-x86_64/egg/tigramite/independence_tests
copying build/lib/tigramite/independence_tests/cmisymb.py -> build/bdist.macosx-10.9-x86_64/egg/tigramite/independence_tests
copying build/lib/tigramite/independence_tests/oracle_conditional_independence.py -> build/bdist.macosx-10.9-x86_64/egg/tigramite/independence_tests
copying build/lib/tigramite/independence_tests/cmiknn.py -> build/bdist.macosx-10.9-x86_64/egg/tigramite/independence_tests
copying build/lib/tigramite/independence_tests/gpdc.py -> build/bdist.macosx-10.9-x86_64/egg/tigramite/independence_tests
byte-compiling build/bdist.macosx-10.9-x86_64/egg/tigramite/lpcmci.py to lpcmci.cpython-39.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/tigramite/models.py to models.cpython-39.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/tigramite/pcmci.py to pcmci.cpython-39.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/tigramite/plotting.py to plotting.cpython-39.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/tigramite/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/tigramite/causal_effects.py to causal_effects.cpython-39.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/tigramite/data_processing.py to data_processing.cpython-39.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/tigramite/independence_tests/independence_tests_base.py to independence_tests_base.cpython-39.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/tigramite/independence_tests/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/tigramite/independence_tests/parcorr.py to parcorr.cpython-39.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/tigramite/independence_tests/LBFGS.py to LBFGS.cpython-39.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/tigramite/independence_tests/gpdc_torch.py to gpdc_torch.cpython-39.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/tigramite/independence_tests/cmisymb.py to cmisymb.cpython-39.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/tigramite/independence_tests/oracle_conditional_independence.py to oracle_conditional_independence.cpython-39.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/tigramite/independence_tests/cmiknn.py to cmiknn.cpython-39.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/tigramite/independence_tests/gpdc.py to gpdc.cpython-39.pyc
creating build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying tigramite.egg-info/PKG-INFO -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying tigramite.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying tigramite.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying tigramite.egg-info/requires.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying tigramite.egg-info/top_level.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/tigramite-4.3.1.1-py3.9.egg' and adding 'build/bdist.macosx-10.9-x86_64/egg' to it
removing 'build/bdist.macosx-10.9-x86_64/egg' (and everything under it)
Processing tigramite-4.3.1.1-py3.9.egg
Copying tigramite-4.3.1.1-py3.9.egg to /Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/site-packages
Adding tigramite 4.3.1.1 to easy-install.pth file

Installed /Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/site-packages/tigramite-4.3.1.1-py3.9.egg
Processing dependencies for tigramite==4.3.1.1
Searching for numba>=0.53.1
Reading https://pypi.org/simple/numba/
/Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/site-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
Downloading https://files.pythonhosted.org/packages/d3/93/05c88fc9f17655a93428f49646d1086c8b2b98e8531033f13f3fe464fae5/numba-0.54.1.tar.gz#sha256=f9dfc803c864edcc2381219b800abf366793400aea55e26d4d5b7d953e14f43f
Best match: numba 0.54.1
Processing numba-0.54.1.tar.gz
Writing /var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/easy_install-o9hezm98/numba-0.54.1/setup.cfg
Running numba-0.54.1/setup.py -q bdist_egg --dist-dir /var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/easy_install-o9hezm98/numba-0.54.1/egg-dist-tmp-4tliqn6n
TBB not found
Using OpenMP from: /Users/deborahkhider/opt/anaconda3/envs/causality
/Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/site-packages/setuptools/__init__.py:148: SetuptoolsDeprecationWarning: setup_requires is deprecated. Supply build dependencies using PEP 517 pyproject.toml build-requires.
  warnings.warn(
warning: no files found matching '*.inc' under directory 'numba'
warning: no files found matching '*.ipynb' under directory 'docs'
warning: no files found matching '*.py' under directory 'examples'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/gh-pages'
/Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
error: Setup script exited with error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/deborahkhider/opt/anaconda3/envs/causality/include -fPIC -O2 -isystem /Users/deborahkhider/opt/anaconda3/envs/causality/include -I/Users/deborahkhider/opt/anaconda3/envs/causality/include/python3.9 -c numba/np/ufunc/gufunc_scheduler.cpp -o build/temp.macosx-10.9-x86_64-3.9/numba/np/ufunc/gufunc_scheduler.o -fopenmp -std=c++11" failed with exit status 1
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/multiprocessing/synchronize.py", line 86, in _cleanup
    from .resource_tracker import unregister
ImportError: cannot import name 'unregister' from partially initialized module 'multiprocessing.resource_tracker' (most likely due to a circular import) (/Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/multiprocessing/resource_tracker.py)
Traceback (most recent call last):
  File "/Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/mp-3ck0ns64'
(causality) 169-231-146-156:tigramite deborahkhider$ /Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/Users/deborahkhider/opt/anaconda3/envs/causality/lib/python3.9/multiprocessing/resource_tracker.py:229: UserWarning: resource_tracker: '/mp-3ck0ns64': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
  ```
  
  Infrastructure:
macOS Big Sur 11.6
Python: 3.9

**Comment by sagarsimha** [comment]
Can you try out the 'developer' branch and let me know if the problem persists?

**Comment by khider** [comment]
We tried that. Python 3.9 is the problem. Worked on 3.7

**Comment by sagarsimha** [comment]
Hello. Looking through the errors with python 3.9, all the three instances you've tried points towards clang (specifically clang: error: unsupported option '-fopenmp'). In case of the current master version, clang is used in cython and in the developer version, numba (with llvm) uses clang. This seems to be a known issue with Mac. See link below,

https://stackoverflow.com/questions/60005176/how-to-deal-with-clang-error-unsupported-option-fopenmp-on-travis

However, I'm still looking into why it worked with python 3.7 on Mac.

I have successfully installed and tested Tigramite with python 3.7 and 3.9 on Ubuntu. So this seems to be specific to Mac OS. Could you let us know if the method in the stackoverflow above solves the issue on 3.9?
